import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    home: 'Home', products: 'Products', about: 'About Us', howToUse: 'How To Use',
    achievements: 'Achievements', contact: 'Contact', getQuote: 'Get a Quote',
    certified: 'ISO 9001:2015 Certified', yearsExcellence: 'Years of Excellence',
    premium: 'Premium', siliconeSealants: 'Silicone Sealants',
    builtForPerfection: 'Built for Perfection',
    heroDescription: 'Leading manufacturer of high-performance silicone sealants and adhesives, trusted by construction professionals worldwide since 1999.',
    exploreProducts: 'Explore Products', yearsExperienceShort: 'Years Experience',
    productLines: 'Product Lines', countriesServed: 'Countries Served',
    ourProducts: 'Our Products', featuredProductLines: 'Featured Product Lines',
    viewDetails: 'View Details', viewAllProducts: 'View All Products',
    quickLinks: 'Quick Links', address: 'Address', contactUs: 'Contact Us',
    applications: 'Applications', solutionsForEveryProject: 'Solutions for Every Project',
    applicationsDesc: 'From high-rise buildings to residential homes, our sealants deliver exceptional performance across all applications.',
    curtainWall: 'Curtain Wall Systems', curtainWallDesc: 'High-performance structural sealants for glass curtain walls, aluminum facades, and modern architectural projects.',
    doorsWindows: 'Doors & Windows', doorsWindowsDesc: 'Weather-resistant sealants ensuring airtight and watertight seals for residential and commercial installations.',
    bathroomKitchen: 'Bathroom & Kitchen', bathroomKitchenDesc: 'Anti-mildew, waterproof sealants designed for wet environments with long-lasting performance.',
    solarRoof: 'Solar & Roofing', solarRoofDesc: 'UV-stable, weatherproof sealants for solar panel installations and roofing applications.',
    recommendedProducts: 'Recommended Products:', trustedWorldwide: 'Trusted by thousands of professionals worldwide',
    whyJinyibai: 'Why Jinyibai', professionalsChoice: "The Professional's Choice",
    whyChooseDesc: 'Discover why leading construction companies and contractors trust Jinyibai for their sealing solutions.',
    stateOfArtManufacturing: 'State-of-the-Art Manufacturing', manufacturingDesc: 'Modern automated production lines with international-standard equipment and rigorous quality control.',
    isoCertified: 'ISO 9001:2015 Certified', isoDesc: 'Internationally recognized quality management system ensuring consistent excellence in every product.',
    advancedRD: 'Advanced R&D Center', rdDesc: 'Continuous innovation with dedicated research team developing cutting-edge sealant formulations.',
    globalDistribution: 'Global Distribution Network', distributionDesc: 'Serving customers in 100+ countries with efficient logistics and reliable delivery.',
    yearDurability: '30+ Year Durability', durabilityDesc: 'Premium structural sealants engineered to last decades in the most demanding conditions.',
    yearsExperienceFull: '25 Years Experience', experienceDesc: 'Quarter century of expertise in silicone sealant manufacturing since 1999.',
    cartonsMonthly: 'Cartons Monthly Capacity', productModels: 'Product Models',
    technicalSupport: 'Technical Support', qualityPassRate: 'Quality Pass Rate',
    trustQuality: 'Trust & Quality', certifiedExcellence: 'Internationally Certified Excellence',
    certDesc: 'Our products meet the highest international quality standards, backed by rigorous certifications and industry recognition.',
    qualityManagement: 'Quality Management', environmentalManagement: 'Environmental Management',
    chinaAccreditation: 'China National Accreditation', intlAccreditation: 'International Accreditation',
    buildingAssociation: 'Building Decoration Association', nationalCompliance: 'National Standard Compliance',
    ourFacility: 'Our Facility', worldClassManufacturing: 'World-Class Manufacturing',
    facilityDesc: 'State-of-the-art production facility in Foshan, Guangdong Province',
    productionFacility: 'Production Facility', qualityLab: 'Quality Control Lab',
    manufacturingLine: 'Manufacturing Line', factoryLocation: 'Factory Location',
    factoryArea: 'Factory Area', employees: 'Employees', productionLines: 'Production Lines',
    certifications: 'Certifications', readyToSeal: 'Ready to Seal the Deal?',
    ctaDesc: 'Get in touch with our expert team for personalized product recommendations, bulk pricing, and OEM services.',
    requestQuote: 'Request a Quote', talkToSales: 'Talk to Sales'
  },
  zh: {
    home: '首页', products: '产品', about: '关于我们', howToUse: '使用方法',
    achievements: '荣誉成就', contact: '联系我们', getQuote: '获取报价',
    certified: 'ISO 9001:2015 认证', yearsExcellence: '年卓越经验',
    premium: '优质', siliconeSealants: '硅酮密封胶',
    builtForPerfection: '追求完美',
    heroDescription: '自1999年以来，值得全球建筑专业人士信赖的高性能硅酮密封胶和粘合剂的领先制造商。',
    exploreProducts: '探索产品', yearsExperienceShort: '年经验',
    productLines: '产品线', countriesServed: '服务国家',
    ourProducts: '我们的产品', featuredProductLines: '特色产品系列',
    viewDetails: '查看详情', viewAllProducts: '查看所有产品',
    quickLinks: '快速链接', address: '地址', contactUs: '联系我们',
    applications: '应用领域', solutionsForEveryProject: '适用于各种项目',
    applicationsDesc: '从高层建筑到住宅，我们的密封胶在所有应用中都提供卓越性能。',
    curtainWall: '幕墙系统', curtainWallDesc: '用于玻璃幕墙、铝制外墙和现代建筑项目的高性能结构密封胶。',
    doorsWindows: '门窗', doorsWindowsDesc: '耐候密封胶，确保住宅和商业安装的气密性和防水性。',
    bathroomKitchen: '浴室和厨房', bathroomKitchenDesc: '专为潮湿环境设计的防霉防水密封胶，性能持久。',
    solarRoof: '太阳能和屋顶', solarRoofDesc: '用于太阳能电池板安装和屋顶应用的抗紫外线、防风雨密封胶。',
    recommendedProducts: '推荐产品：', trustedWorldwide: '受到全球数千名专业人士的信赖',
    whyJinyibai: '为什么选择金益百', professionalsChoice: '专业人士的选择',
    whyChooseDesc: '了解为什么领先的建筑公司和承包商信赖金益百的密封解决方案。',
    stateOfArtManufacturing: '先进制造', manufacturingDesc: '现代化自动生产线，配备国际标准设备和严格质量控制。',
    isoCertified: 'ISO 9001:2015 认证', isoDesc: '国际认可的质量管理体系，确保每个产品始终如一的卓越品质。',
    advancedRD: '先进研发中心', rdDesc: '专业研发团队持续创新，开发前沿密封胶配方。',
    globalDistribution: '全球分销网络', distributionDesc: '为100多个国家的客户提供高效物流和可靠交付。',
    yearDurability: '30年+耐用性', durabilityDesc: '优质结构密封胶，在最苛刻的条件下可使用数十年。',
    yearsExperienceFull: '25年经验', experienceDesc: '自1999年以来，在硅酮密封胶制造领域拥有四分之一世纪的专业知识。',
    cartonsMonthly: '月产能（箱）', productModels: '产品型号',
    technicalSupport: '技术支持', qualityPassRate: '质量合格率',
    trustQuality: '信任与质量', certifiedExcellence: '国际认证卓越',
    certDesc: '我们的产品符合最高国际质量标准，并获得严格认证和行业认可。',
    qualityManagement: '质量管理', environmentalManagement: '环境管理',
    chinaAccreditation: '中国国家认证', intlAccreditation: '国际认证',
    buildingAssociation: '建筑装饰协会', nationalCompliance: '国家标准合规',
    ourFacility: '我们的工厂', worldClassManufacturing: '世界一流制造',
    facilityDesc: '位于广东省佛山市的先进生产设施',
    productionFacility: '生产设施', qualityLab: '质量控制实验室',
    manufacturingLine: '生产线', factoryLocation: '工厂位置',
    factoryArea: '工厂面积', employees: '员工', productionLines: '生产线',
    certifications: '认证', readyToSeal: '准备好合作了吗？',
    ctaDesc: '联系我们的专家团队，获取个性化产品推荐、批量定价和OEM服务。',
    requestQuote: '索取报价', talkToSales: '联系销售'
  },
  es: {
    home: 'Inicio', products: 'Productos', about: 'Sobre Nosotros', howToUse: 'Cómo Usar',
    achievements: 'Logros', contact: 'Contacto', getQuote: 'Solicitar Cotización',
    certified: 'Certificado ISO 9001:2015', yearsExcellence: 'Años de Excelencia',
    premium: 'Premium', siliconeSealants: 'Selladores de Silicona',
    builtForPerfection: 'Construido para la Perfección',
    heroDescription: 'Fabricante líder de selladores de silicona de alto rendimiento, confiado por profesionales desde 1999.',
    exploreProducts: 'Explorar Productos', yearsExperienceShort: 'Años de Experiencia',
    productLines: 'Líneas de Productos', countriesServed: 'Países Atendidos',
    ourProducts: 'Nuestros Productos', featuredProductLines: 'Productos Destacados',
    viewDetails: 'Ver Detalles', viewAllProducts: 'Ver Todos',
    quickLinks: 'Enlaces', address: 'Dirección', contactUs: 'Contáctenos',
    applications: 'Aplicaciones', solutionsForEveryProject: 'Soluciones para Cada Proyecto',
    applicationsDesc: 'Desde edificios de gran altura hasta casas residenciales, nuestros selladores ofrecen rendimiento excepcional.',
    curtainWall: 'Sistemas de Muro Cortina', curtainWallDesc: 'Selladores estructurales de alto rendimiento para muros cortina de vidrio y fachadas modernas.',
    doorsWindows: 'Puertas y Ventanas', doorsWindowsDesc: 'Selladores resistentes a la intemperie que garantizan sellos herméticos para instalaciones residenciales y comerciales.',
    bathroomKitchen: 'Baño y Cocina', bathroomKitchenDesc: 'Selladores impermeables y antimoho diseñados para ambientes húmedos con rendimiento duradero.',
    solarRoof: 'Solar y Techos', solarRoofDesc: 'Selladores resistentes a los rayos UV e impermeables para instalaciones de paneles solares y techos.',
    recommendedProducts: 'Productos Recomendados:', trustedWorldwide: 'Confiado por miles de profesionales en todo el mundo',
    whyJinyibai: 'Por Qué Jinyibai', professionalsChoice: 'La Elección de los Profesionales',
    whyChooseDesc: 'Descubra por qué las empresas constructoras líderes confían en Jinyibai.',
    stateOfArtManufacturing: 'Fabricación de Vanguardia', manufacturingDesc: 'Líneas de producción automatizadas modernas con equipos de estándar internacional.',
    isoCertified: 'Certificado ISO 9001:2015', isoDesc: 'Sistema de gestión de calidad reconocido internacionalmente.',
    advancedRD: 'Centro de I+D Avanzado', rdDesc: 'Innovación continua con equipo de investigación dedicado.',
    globalDistribution: 'Red de Distribución Global', distributionDesc: 'Servicio a clientes en más de 100 países.',
    yearDurability: 'Durabilidad de 30+ Años', durabilityDesc: 'Selladores estructurales premium diseñados para durar décadas.',
    yearsExperienceFull: '25 Años de Experiencia', experienceDesc: 'Un cuarto de siglo de experiencia en fabricación de selladores de silicona desde 1999.',
    cartonsMonthly: 'Capacidad Mensual', productModels: 'Modelos de Productos',
    technicalSupport: 'Soporte Técnico', qualityPassRate: 'Tasa de Aprobación de Calidad',
    trustQuality: 'Confianza y Calidad', certifiedExcellence: 'Excelencia Certificada Internacionalmente',
    certDesc: 'Nuestros productos cumplen con los más altos estándares internacionales de calidad.',
    qualityManagement: 'Gestión de Calidad', environmentalManagement: 'Gestión Ambiental',
    chinaAccreditation: 'Acreditación Nacional de China', intlAccreditation: 'Acreditación Internacional',
    buildingAssociation: 'Asociación de Decoración de Edificios', nationalCompliance: 'Cumplimiento del Estándar Nacional',
    ourFacility: 'Nuestra Instalación', worldClassManufacturing: 'Fabricación de Clase Mundial',
    facilityDesc: 'Instalación de producción de última generación en Foshan, Provincia de Guangdong',
    productionFacility: 'Instalación de Producción', qualityLab: 'Laboratorio de Control de Calidad',
    manufacturingLine: 'Línea de Fabricación', factoryLocation: 'Ubicación de la Fábrica',
    factoryArea: 'Área de Fábrica', employees: 'Empleados', productionLines: 'Líneas de Producción',
    certifications: 'Certificaciones', readyToSeal: '¿Listo para Cerrar el Trato?',
    ctaDesc: 'Póngase en contacto con nuestro equipo de expertos para recomendaciones de productos personalizadas.',
    requestQuote: 'Solicitar Cotización', talkToSales: 'Hablar con Ventas'
  },
  ar: {
    home: 'الرئيسية', products: 'المنتجات', about: 'من نحن', howToUse: 'كيفية الاستخدام',
    achievements: 'الإنجازات', contact: 'اتصل بنا', getQuote: 'احصل على عرض',
    certified: 'معتمد ISO 9001:2015', yearsExcellence: 'سنوات من التميز',
    premium: 'ممتاز', siliconeSealants: 'مواد منع التسرب',
    builtForPerfection: 'مصمم للكمال',
    heroDescription: 'الشركة الرائدة في تصنيع مواد منع التسرب السيليكونية عالية الأداء منذ 1999.',
    exploreProducts: 'استكشف المنتجات', yearsExperienceShort: 'سنوات الخبرة',
    productLines: 'خطوط الإنتاج', countriesServed: 'الدول المخدومة',
    ourProducts: 'منتجاتنا', featuredProductLines: 'المنتجات المميزة',
    viewDetails: 'عرض التفاصيل', viewAllProducts: 'عرض الكل',
    quickLinks: 'روابط سريعة', address: 'العنوان', contactUs: 'اتصل بنا',
    applications: 'التطبيقات', solutionsForEveryProject: 'حلول لكل مشروع',
    applicationsDesc: 'من المباني الشاهقة إلى المنازل السكنية، توفر مواد منع التسرب لدينا أداءً استثنائيًا.',
    curtainWall: 'أنظمة الجدران الستارية', curtainWallDesc: 'مواد منع تسرب هيكلية عالية الأداء للجدران الستارية الزجاجية والواجهات الحديثة.',
    doorsWindows: 'الأبواب والنوافذ', doorsWindowsDesc: 'مواد منع تسرب مقاومة للطقس تضمن إحكام الإغلاق للتركيبات السكنية والتجارية.',
    bathroomKitchen: 'الحمام والمطبخ', bathroomKitchenDesc: 'مواد منع تسرب مقاومة للعفن ومقاومة للماء مصممة للبيئات الرطبة.',
    solarRoof: 'الطاقة الشمسية والأسقف', solarRoofDesc: 'مواد منع تسرب مستقرة ضد الأشعة فوق البنفسجية ومقاومة للعوامل الجوية.',
    recommendedProducts: 'المنتجات الموصى بها:', trustedWorldwide: 'موثوق به من قبل آلاف المحترفين في جميع أنحاء العالم',
    whyJinyibai: 'لماذا جينييباي', professionalsChoice: 'اختيار المحترفين',
    whyChooseDesc: 'اكتشف لماذا تثق شركات البناء الرائدة في جينييباي لحلول منع التسرب.',
    stateOfArtManufacturing: 'التصنيع الحديث', manufacturingDesc: 'خطوط إنتاج آلية حديثة مع معدات بمعايير دولية.',
    isoCertified: 'معتمد ISO 9001:2015', isoDesc: 'نظام إدارة جودة معترف به دوليًا.',
    advancedRD: 'مركز بحث وتطوير متقدم', rdDesc: 'ابتكار مستمر مع فريق بحث مخصص.',
    globalDistribution: 'شبكة توزيع عالمية', distributionDesc: 'خدمة العملاء في أكثر من 100 دولة.',
    yearDurability: 'متانة 30+ سنة', durabilityDesc: 'مواد منع تسرب هيكلية متميزة مصممة لتدوم لعقود.',
    yearsExperienceFull: '25 سنة من الخبرة', experienceDesc: 'ربع قرن من الخبرة في تصنيع مواد منع التسرب السيليكونية منذ 1999.',
    cartonsMonthly: 'الطاقة الإنتاجية الشهرية', productModels: 'نماذج المنتجات',
    technicalSupport: 'الدعم الفني', qualityPassRate: 'معدل اجتياز الجودة',
    trustQuality: 'الثقة والجودة', certifiedExcellence: 'التميز المعتمد دوليًا',
    certDesc: 'منتجاتنا تلبي أعلى معايير الجودة الدولية.',
    qualityManagement: 'إدارة الجودة', environmentalManagement: 'الإدارة البيئية',
    chinaAccreditation: 'الاعتماد الوطني الصيني', intlAccreditation: 'الاعتماد الدولي',
    buildingAssociation: 'جمعية تزيين المباني', nationalCompliance: 'الامتثال للمعايير الوطنية',
    ourFacility: 'منشأتنا', worldClassManufacturing: 'تصنيع عالمي المستوى',
    facilityDesc: 'مرفق إنتاج حديث في فوشان، مقاطعة قوانغدونغ',
    productionFacility: 'مرفق الإنتاج', qualityLab: 'مختبر مراقبة الجودة',
    manufacturingLine: 'خط التصنيع', factoryLocation: 'موقع المصنع',
    factoryArea: 'مساحة المصنع', employees: 'الموظفون', productionLines: 'خطوط الإنتاج',
    certifications: 'الشهادات', readyToSeal: 'مستعد لإتمام الصفقة؟',
    ctaDesc: 'تواصل مع فريق الخبراء لدينا للحصول على توصيات منتجات مخصصة.',
    requestQuote: 'طلب عرض أسعار', talkToSales: 'التحدث إلى المبيعات'
  },
  fr: {
    home: 'Accueil', products: 'Produits', about: 'À Propos', howToUse: 'Mode d\'emploi',
    achievements: 'Réalisations', contact: 'Contact', getQuote: 'Obtenir un Devis',
    certified: 'Certifié ISO 9001:2015', yearsExcellence: 'Années d\'Excellence',
    premium: 'Premium', siliconeSealants: 'Mastics Silicone',
    builtForPerfection: 'Conçu pour la Perfection',
    heroDescription: 'Fabricant leader de mastics silicone haute performance depuis 1999.',
    exploreProducts: 'Découvrir', yearsExperienceShort: 'Ans d\'Expérience',
    productLines: 'Gammes', countriesServed: 'Pays Desservis',
    ourProducts: 'Nos Produits', featuredProductLines: 'Produits Vedettes',
    viewDetails: 'Voir Détails', viewAllProducts: 'Voir Tout',
    quickLinks: 'Liens Rapides', address: 'Adresse', contactUs: 'Contactez-nous',
    applications: 'Applications', solutionsForEveryProject: 'Solutions pour Chaque Projet',
    applicationsDesc: 'Des immeubles de grande hauteur aux maisons résidentielles, nos mastics offrent des performances exceptionnelles.',
    curtainWall: 'Systèmes de Murs-Rideaux', curtainWallDesc: 'Mastics structuraux haute performance pour murs-rideaux en verre et façades modernes.',
    doorsWindows: 'Portes et Fenêtres', doorsWindowsDesc: 'Mastics résistants aux intempéries assurant des joints étanches pour installations résidentielles et commerciales.',
    bathroomKitchen: 'Salle de Bain et Cuisine', bathroomKitchenDesc: 'Mastics anti-moisissures et imperméables conçus pour environnements humides.',
    solarRoof: 'Solaire et Toiture', solarRoofDesc: 'Mastics stables aux UV et résistants aux intempéries pour panneaux solaires et toitures.',
    recommendedProducts: 'Produits Recommandés:', trustedWorldwide: 'Approuvé par des milliers de professionnels dans le monde',
    whyJinyibai: 'Pourquoi Jinyibai', professionalsChoice: 'Le Choix des Professionnels',
    whyChooseDesc: 'Découvrez pourquoi les entreprises de construction leaders font confiance à Jinyibai.',
    stateOfArtManufacturing: 'Fabrication de Pointe', manufacturingDesc: 'Lignes de production automatisées modernes avec équipements standards internationaux.',
    isoCertified: 'Certifié ISO 9001:2015', isoDesc: 'Système de gestion de la qualité reconnu internationalement.',
    advancedRD: 'Centre R&D Avancé', rdDesc: 'Innovation continue avec équipe de recherche dédiée.',
    globalDistribution: 'Réseau de Distribution Mondial', distributionDesc: 'Service aux clients dans plus de 100 pays.',
    yearDurability: 'Durabilité 30+ Ans', durabilityDesc: 'Mastics structuraux premium conçus pour durer des décennies.',
    yearsExperienceFull: '25 Ans d\'Expérience', experienceDesc: 'Un quart de siècle d\'expertise dans la fabrication de mastics silicone depuis 1999.',
    cartonsMonthly: 'Capacité Mensuelle', productModels: 'Modèles de Produits',
    technicalSupport: 'Support Technique', qualityPassRate: 'Taux de Réussite Qualité',
    trustQuality: 'Confiance et Qualité', certifiedExcellence: 'Excellence Certifiée Internationalement',
    certDesc: 'Nos produits répondent aux plus hauts standards internationaux de qualité.',
    qualityManagement: 'Gestion de la Qualité', environmentalManagement: 'Gestion Environnementale',
    chinaAccreditation: 'Accréditation Nationale de Chine', intlAccreditation: 'Accréditation Internationale',
    buildingAssociation: 'Association de Décoration du Bâtiment', nationalCompliance: 'Conformité aux Normes Nationales',
    ourFacility: 'Notre Installation', worldClassManufacturing: 'Fabrication de Classe Mondiale',
    facilityDesc: 'Installation de production de pointe à Foshan, Province du Guangdong',
    productionFacility: 'Installation de Production', qualityLab: 'Laboratoire de Contrôle Qualité',
    manufacturingLine: 'Ligne de Fabrication', factoryLocation: 'Emplacement de l\'Usine',
    factoryArea: 'Superficie de l\'Usine', employees: 'Employés', productionLines: 'Lignes de Production',
    certifications: 'Certifications', readyToSeal: 'Prêt à Conclure l\'Affaire?',
    ctaDesc: 'Contactez notre équipe d\'experts pour des recommandations de produits personnalisées.',
    requestQuote: 'Demander un Devis', talkToSales: 'Parler aux Ventes'
  },
  de: {
    home: 'Startseite', products: 'Produkte', about: 'Über Uns', howToUse: 'Anwendung',
    achievements: 'Auszeichnungen', contact: 'Kontakt', getQuote: 'Angebot Anfordern',
    certified: 'ISO 9001:2015 Zertifiziert', yearsExcellence: 'Jahre Exzellenz',
    premium: 'Premium', siliconeSealants: 'Silikondichtstoffe',
    builtForPerfection: 'Für Perfektion',
    heroDescription: 'Führender Hersteller von Hochleistungs-Silikondichtstoffen seit 1999.',
    exploreProducts: 'Produkte Erkunden', yearsExperienceShort: 'Jahre Erfahrung',
    productLines: 'Produktlinien', countriesServed: 'Länder',
    ourProducts: 'Unsere Produkte', featuredProductLines: 'Produktlinien',
    viewDetails: 'Details', viewAllProducts: 'Alle Anzeigen',
    quickLinks: 'Schnelllinks', address: 'Adresse', contactUs: 'Kontakt',
    applications: 'Anwendungen', solutionsForEveryProject: 'Lösungen für Jedes Projekt',
    applicationsDesc: 'Von Hochhäusern bis zu Wohnhäusern bieten unsere Dichtstoffe außergewöhnliche Leistung.',
    curtainWall: 'Vorhangfassadensysteme', curtainWallDesc: 'Hochleistungs-Strukturdichtstoffe für Glasfassaden und moderne Architekturprojekte.',
    doorsWindows: 'Türen und Fenster', doorsWindowsDesc: 'Wetterbeständige Dichtstoffe für luft- und wasserdichte Abdichtungen.',
    bathroomKitchen: 'Bad und Küche', bathroomKitchenDesc: 'Schimmelresistente, wasserdichte Dichtstoffe für feuchte Umgebungen.',
    solarRoof: 'Solar und Dach', solarRoofDesc: 'UV-stabile, wetterfeste Dichtstoffe für Solaranlagen und Dachanwendungen.',
    recommendedProducts: 'Empfohlene Produkte:', trustedWorldwide: 'Von Tausenden von Fachleuten weltweit vertraut',
    whyJinyibai: 'Warum Jinyibai', professionalsChoice: 'Die Wahl der Profis',
    whyChooseDesc: 'Entdecken Sie, warum führende Bauunternehmen Jinyibai vertrauen.',
    stateOfArtManufacturing: 'Modernste Fertigung', manufacturingDesc: 'Moderne automatisierte Produktionslinien mit internationalen Standardgeräten.',
    isoCertified: 'ISO 9001:2015 Zertifiziert', isoDesc: 'International anerkanntes Qualitätsmanagementsystem.',
    advancedRD: 'Fortgeschrittenes F&E-Zentrum', rdDesc: 'Kontinuierliche Innovation mit dediziertem Forschungsteam.',
    globalDistribution: 'Globales Vertriebsnetz', distributionDesc: 'Service für Kunden in über 100 Ländern.',
    yearDurability: '30+ Jahre Haltbarkeit', durabilityDesc: 'Premium-Strukturdichtstoffe für jahrzehntelange Haltbarkeit.',
    yearsExperienceFull: '25 Jahre Erfahrung', experienceDesc: 'Ein Vierteljahrhundert Expertise in der Herstellung von Silikondichtstoffen seit 1999.',
    cartonsMonthly: 'Monatliche Kapazität', productModels: 'Produktmodelle',
    technicalSupport: 'Technischer Support', qualityPassRate: 'Qualitäts-Erfolgsquote',
    trustQuality: 'Vertrauen und Qualität', certifiedExcellence: 'International Zertifizierte Exzellenz',
    certDesc: 'Unsere Produkte erfüllen die höchsten internationalen Qualitätsstandards.',
    qualityManagement: 'Qualitätsmanagement', environmentalManagement: 'Umweltmanagement',
    chinaAccreditation: 'Chinesische Nationale Akkreditierung', intlAccreditation: 'Internationale Akkreditierung',
    buildingAssociation: 'Baudekorationsverband', nationalCompliance: 'Nationale Standardkonformität',
    ourFacility: 'Unsere Anlage', worldClassManufacturing: 'Weltklasse-Fertigung',
    facilityDesc: 'Hochmoderne Produktionsanlage in Foshan, Provinz Guangdong',
    productionFacility: 'Produktionsanlage', qualityLab: 'Qualitätskontrolllabor',
    manufacturingLine: 'Fertigungslinie', factoryLocation: 'Werksstandort',
    factoryArea: 'Werksfläche', employees: 'Mitarbeiter', productionLines: 'Produktionslinien',
    certifications: 'Zertifizierungen', readyToSeal: 'Bereit zum Abschluss?',
    ctaDesc: 'Kontaktieren Sie unser Expertenteam für personalisierte Produktempfehlungen.',
    requestQuote: 'Angebot Anfordern', talkToSales: 'Mit Vertrieb Sprechen'
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');
  const t = (key) => translations[language]?.[key] || translations.en[key] || key;
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}